-- ============================================
-- SPEC — TASK 1 supplement : health_records (minimal)
-- รันเสริมจาก docs/supabase_full_migration.sql
-- ครอบคลุมสเปค Master Prompt TASK 1 แบบตรงตัว
-- ============================================

-- 1) system_settings — ปรับ default ให้ตรงสเปค (ถ้ายังไม่มีแถว)
-- สเปคต้องการ default:
--   maintenance_title   = 'แจ้งปิดปรับปรุงระบบชั่วคราว'
--   maintenance_message = 'ขณะนี้ระบบกำลังย้ายฐานข้อมูลเพื่อเพิ่มความเร็วในการใช้งาน คาดว่าจะเปิดให้บริการวันพรุ่งนี้ เวลา 06:00 น.'
-- ไฟล์หลักใช้ข้อความย่อกว่า — อัปเดตให้ตรงสเปคถ้ายังเป็นค่าเดิม
do $$
begin
  update public.system_settings
     set maintenance_title = 'แจ้งปิดปรับปรุงระบบชั่วคราว',
         maintenance_message = 'ขณะนี้ระบบกำลังย้ายฐานข้อมูลเพื่อเพิ่มความเร็วในการใช้งาน คาดว่าจะเปิดให้บริการวันพรุ่งนี้ เวลา 06:00 น.'
   where id = 1
     and maintenance_title = 'ระบบอยู่ระหว่างการปรับปรุง';
end $$;

-- 2) health_records — ตาราง minimal ตามสเปค TASK 1 (สำหรับ Proof-of-Concept / ตัวอย่างง่าย)
-- ระบบจริงของโปรเจกต์ใช้ users + steps_log ที่สมบูรณ์กว่า — ตารางนี้คงไว้เพื่อรองรับสเปคตรงตัว
-- ไม่ชนกับของเดิม: ถ้ามีแล้วจะไม่สร้างซ้ำ
create table if not exists public.health_records (
  id              bigint generated by default as identity primary key,
  id_card         text,
  fullname        text,
  weight          numeric,
  bmi             numeric,
  step_count      int,
  image_drive_id  text, -- เก็บเฉพาะ File ID ของ Google Drive
  created_at      timestamptz not null default now()
);
create index if not exists idx_health_records_id_card on public.health_records(id_card);
create index if not exists idx_health_records_created on public.health_records(created_at desc);

alter table public.health_records enable row level security;
do $$ begin
  drop policy if exists "Allow all health_records" on public.health_records;
  create policy "Allow all health_records" on public.health_records for all using (true) with check (true);
end $$;

-- 3) ตรวจสอบ
-- select * from public.system_settings where id=1;
-- select * from public.health_records limit 5;
