-- ============================================
-- LP Well-being — Full Migration: Google Sheet -> Supabase
-- Run ทั้งไฟล์ใน Supabase SQL Editor (ครั้งเดียว)
-- อ้างอิง docs/09_Google_Sheet_Schema.md + src/types/index.ts
-- ============================================

-- 0) Extension ที่ต้องใช้
create extension if not exists "pgcrypto";

-- ============================================
-- 1) system_settings (มีแล้วจากไฟล์ก่อน แต่ใส่ IF NOT EXISTS ไว้)
-- ============================================
create table if not exists public.system_settings (
  id                    bigint generated by default as identity primary key,
  is_maintenance_active boolean not null default true,
  maintenance_title     text    not null default 'ระบบอยู่ระหว่างการปรับปรุง',
  maintenance_message   text    not null default 'เรากำลังปรับปรุงระบบเพื่อประสบการณ์ที่ดีขึ้น กรุณากลับมาใหม่ในภายหลัง ขออภัยในความไม่สะดวก',
  updated_at            timestamptz not null default now(),
  updated_by            text,
  created_at            timestamptz not null default now()
);
-- ถ้าตารางเคยสร้างแบบ GENERATED ALWAYS ไว้แล้ว ให้แปลงก่อน
do $$ begin
  begin alter table public.system_settings alter column id drop identity; exception when others then null; end;
  begin alter table public.system_settings alter column id add generated by default as identity; exception when others then null; end;
end $$;
insert into public.system_settings (id, is_maintenance_active, maintenance_title, maintenance_message)
values (1, true, 'ระบบอยู่ระหว่างการปรับปรุง', 'เรากำลังปรับปรุงระบบเพื่อประสบการณ์ที่ดีขึ้น กรุณากลับมาใหม่ในภายหลัง ขออภัยในความไม่สะดวก')
on conflict (id) do nothing;

-- trigger updated_at
create or replace function public.handle_updated_at() returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end; $$;
drop trigger if exists trg_system_settings_updated_at on public.system_settings;
create trigger trg_system_settings_updated_at before update on public.system_settings
  for each row execute function public.handle_updated_at();

-- ============================================
-- 2) users — บุคลากร (PK = User_ID เลขบัตร ปชช)
-- ============================================
create table if not exists public.users (
  user_id               text primary key, -- เลขบัตร ปชช (เก็บ text กัน leading 0)
  prefix                text,
  full_name             text not null,
  nickname              text,
  position              text,
  department            text, -- 11 ฝ่าย
  birth_date            date,
  gender                text,
  lgbtq_identity        text,
  weight_kg             numeric,
  height_cm             numeric,
  bmi_value             numeric,
  waist_inch            numeric,
  role                  text check (role in ('Admin','Committee','Employee','Head','Executive')) default 'Employee',
  password              text, -- hashed
  total_points          int default 0,
  level                 text default '1',
  personnel_id          text,
  registration_status   text check (registration_status in ('Pending','Registered','Inactive','')) default '',
  created_by            text,
  created_date          date,
  first_name            text,
  last_name             text,
  profile_image         text, -- Drive ID หรือ URL
  activities            text,
  step_record_mode      text check (step_record_mode in ('1','2')),
  device_token          text,
  device_updated_at     timestamptz,
  created_at            timestamptz not null default now(),
  updated_at            timestamptz not null default now()
);
drop trigger if exists trg_users_updated_at on public.users;
create trigger trg_users_updated_at before update on public.users for each row execute function public.handle_updated_at();
create index if not exists idx_users_department on public.users(department);
create index if not exists idx_users_role on public.users(role);

-- ============================================
-- 3) steps_log — บันทึกก้าว (Record_ID = UUID)
-- ============================================
create table if not exists public.steps_log (
  record_id       text primary key, -- ใช้ UUID string จาก Sheet เดิม
  user_id         text not null references public.users(user_id) on delete cascade,
  date_thai       date not null, -- เก็บ ค.ศ. (แปลง พ.ศ.-543 ก่อน insert)
  steps_count     int  not null check (steps_count >= 0),
  submitted_steps int,
  record_method   text, -- Google Fit / Manual / ภาพถ่าย
  image_drive_id  text, -- Drive ID -> ย้ายไป Storage ทีหลังได้
  status          text check (status in ('Pending','Approved','Rejected','Deleted')) default 'Pending',
  week_number     int,
  auditor_id      text references public.users(user_id),
  reviewed_at     timestamptz,
  recorded_at     timestamptz default now(),
  reject_reason   text,
  ai_steps        int,
  ai_confidence   numeric,
  date_match      boolean,
  alert_flag      boolean default false,
  alert_reason    text,
  notes           text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
drop trigger if exists trg_steps_log_updated_at on public.steps_log;
create trigger trg_steps_log_updated_at before update on public.steps_log for each row execute function public.handle_updated_at();
create index if not exists idx_steps_user_date on public.steps_log(user_id, date_thai);
create index if not exists idx_steps_status on public.steps_log(status);
create index if not exists idx_steps_date on public.steps_log(date_thai);

-- ============================================
-- 4) sweet_free — พุธนี้ไม่มีเชื่อม
-- ============================================
create table if not exists public.sweet_free (
  entry_id       text primary key,
  user_id        text not null references public.users(user_id) on delete cascade,
  wednesday_date date not null,
  status         boolean not null, -- true=งดได้
  logged_by      text references public.users(user_id),
  reason         text,
  recorded_at    timestamptz default now(),
  created_at     timestamptz not null default now(),
  unique(user_id, wednesday_date)
);
create index if not exists idx_sweet_user on public.sweet_free(user_id);
create index if not exists idx_sweet_date on public.sweet_free(wednesday_date);

-- ============================================
-- 5) baseline_records — น้ำหนักตั้งต้น (ถ้ามีชีท Baseline)
-- ============================================
create table if not exists public.baseline_records (
  record_id   text primary key,
  user_id     text not null references public.users(user_id) on delete cascade,
  weight_kg   numeric not null,
  height_cm   numeric,
  bmi_value   numeric,
  source      text,
  recorded_at timestamptz default now(),
  created_at  timestamptz not null default now()
);

-- ============================================
-- 6) weight_after_records — ชั่งหลังโครงการ
-- ============================================
create table if not exists public.weight_after_records (
  record_id   text primary key,
  user_id     text not null references public.users(user_id) on delete cascade,
  weight_kg   numeric not null,
  height_cm   numeric,
  bmi_value   numeric,
  recorded_at timestamptz default now(),
  created_at  timestamptz not null default now()
);

-- ============================================
-- 7) project_settings — ห้วงเวลาโครงการ (project-window)
-- ============================================
create table if not exists public.project_settings (
  id         int primary key default 1,
  start_date date not null default '2026-08-24',
  end_date   date not null default '2026-11-13',
  updated_by text,
  updated_at timestamptz not null default now(),
  check (id = 1), check (start_date <= end_date)
);
insert into public.project_settings (id, start_date, end_date) values (1, '2026-08-24','2026-11-13') on conflict (id) do nothing;
drop trigger if exists trg_project_settings_updated_at on public.project_settings;
create trigger trg_project_settings_updated_at before update on public.project_settings for each row execute function public.handle_updated_at();

-- ============================================
-- 8) google_fit_links — เชื่อม Google Fit (ถ้ามี)
-- ============================================
create table if not exists public.google_fit_links (
  user_id       text primary key references public.users(user_id) on delete cascade,
  google_email  text,
  access_token  text,
  refresh_token text,
  linked_at     timestamptz default now(),
  updated_at    timestamptz not null default now()
);
drop trigger if exists trg_google_fit_updated_at on public.google_fit_links;
create trigger trg_google_fit_updated_at before update on public.google_fit_links for each row execute function public.handle_updated_at();

-- ============================================
-- 9) RLS — เปิดและอนุญาต (ปรับเข้มทีหลังได้)
-- ============================================
alter table public.system_settings enable row level security;
alter table public.users enable row level security;
alter table public.steps_log enable row level security;
alter table public.sweet_free enable row level security;
alter table public.baseline_records enable row level security;
alter table public.weight_after_records enable row level security;
alter table public.project_settings enable row level security;
alter table public.google_fit_links enable row level security;

-- ลบ policy เก่าแล้วสร้างใหม่ (idempotent)
do $$ begin
  -- system_settings: public read, service_role write (ดูไฟล์แยก)
  drop policy if exists "Allow public read system_settings" on public.system_settings;
  create policy "Allow public read system_settings" on public.system_settings for select using (true);
  drop policy if exists "Allow upsert system_settings" on public.system_settings;
  create policy "Allow upsert system_settings" on public.system_settings for all using (true) with check (true);

  -- users: public read (ต้อง login ฝั่ง app), service_role all
  drop policy if exists "Allow public read users" on public.users;
  create policy "Allow public read users" on public.users for select using (true);
  drop policy if exists "Allow all users" on public.users;
  create policy "Allow all users" on public.users for all using (true) with check (true);

  -- steps_log, sweet_free, อื่นๆ: เปิดหมดก่อน ค่อยล็อกทีหลัง
  drop policy if exists "Allow all steps_log" on public.steps_log;
  create policy "Allow all steps_log" on public.steps_log for all using (true) with check (true);
  drop policy if exists "Allow all sweet_free" on public.sweet_free;
  create policy "Allow all sweet_free" on public.sweet_free for all using (true) with check (true);
  drop policy if exists "Allow all baseline" on public.baseline_records;
  create policy "Allow all baseline" on public.baseline_records for all using (true) with check (true);
  drop policy if exists "Allow all weight_after" on public.weight_after_records;
  create policy "Allow all weight_after" on public.weight_after_records for all using (true) with check (true);
  drop policy if exists "Allow all project_settings" on public.project_settings;
  create policy "Allow all project_settings" on public.project_settings for all using (true) with check (true);
  drop policy if exists "Allow all google_fit_links" on public.google_fit_links;
  create policy "Allow all google_fit_links" on public.google_fit_links for all using (true) with check (true);
end $$;

-- ============================================
-- 10) ตรวจสอบ
-- ============================================
-- select table_name from information_schema.tables where table_schema='public' order by table_name;
-- select count(*) from users; select count(*) from steps_log; select count(*) from sweet_free;
