-- ============================================
-- LP Well-being — Maintenance Mode: Supabase Table
-- ตาราง: system_settings
-- วางไฟล์นี้ใน Supabase SQL Editor แล้วกด Run
-- ============================================

-- 1) สร้างตาราง (ถ้ายังไม่มี) — ใช้ BY DEFAULT เพื่อให้ insert id=1 ได้
create table if not exists public.system_settings (
  id                    bigint generated by default as identity primary key,
  is_maintenance_active boolean not null default true,
  maintenance_title     text    not null default 'ระบบอยู่ระหว่างการปรับปรุง',
  maintenance_message   text    not null default 'เรากำลังปรับปรุงระบบเพื่อประสบการณ์ที่ดีขึ้น กรุณากลับมาใหม่ในภายหลัง ขออภัยในความไม่สะดวก',
  updated_at            timestamptz not null default now(),
  updated_by            text,
  created_at            timestamptz not null default now()
);
-- ถ้าตารางเคยสร้างแบบ GENERATED ALWAYS ไว้แล้ว ให้แก้ชนิดก่อน
do $$ begin
  begin alter table public.system_settings alter column id drop identity; exception when others then null; end;
  begin alter table public.system_settings alter column id add generated by default as identity; exception when others then null; end;
end $$;

-- 2) ใส่แถวเริ่มต้น 1 แถว (Singleton pattern) — ถ้ายังไม่มีข้อมูล
insert into public.system_settings (id, is_maintenance_active, maintenance_title, maintenance_message)
values (1, true, 'ระบบอยู่ระหว่างการปรับปรุง', 'เรากำลังปรับปรุงระบบเพื่อประสบการณ์ที่ดีขึ้น กรุณากลับมาใหม่ในภายหลัง ขออภัยในความไม่สะดวก')
on conflict (id) do nothing;

-- 3) บังคับให้มีเพียงแถวเดียว (id=1) — ถ้าต้องการ ลบเงื่อนไขนี้ออกได้ถ้าอยากเก็บหลายแถว
-- (id เป็น PK อยู่แล้ว จึงมีได้แถวละ id — เราใช้ id=1 เป็น singleton)

-- 4) Trigger อัปเดต updated_at อัตโนมัติ
create or replace function public.handle_system_settings_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_system_settings_updated_at on public.system_settings;
create trigger trg_system_settings_updated_at
  before update on public.system_settings
  for each row execute function public.handle_system_settings_updated_at();

-- 5) ปิด RLS ชั่วคราวเพื่อให้ API อ่าน/เขียนได้ทันที (ถ้าเปิด RLS ต้องสร้าง Policy)
-- แนะนำ: เปิด RLS แล้วเพิ่ม policy ด้านล่าง
alter table public.system_settings enable row level security;

-- อนุญาตให้อ่านได้ทุกคน (public read)
drop policy if exists "Allow public read system_settings" on public.system_settings;
create policy "Allow public read system_settings"
  on public.system_settings for select
  using (true);

-- อนุญาตให้ update ได้ทุกคนที่มี service_role (API ฝั่ง server ใช้ service_role key)
-- ถ้าใช้ anon key ต้องสร้าง policy แบบ authenticated หรือเพิ่มเงื่อนไข
drop policy if exists "Allow update system_settings for service_role" on public.system_settings;
create policy "Allow update system_settings for service_role"
  on public.system_settings for update
  using (true) with check (true);

drop policy if exists "Allow insert system_settings for service_role" on public.system_settings;
create policy "Allow insert system_settings for service_role"
  on public.system_settings for insert
  with check (true);

-- 6) ตรวจสอบข้อมูล
-- select * from public.system_settings where id = 1;

-- ============================================
-- วิธีเปลี่ยนรหัสลับ dev_secret
-- ============================================
-- รหัสลับไม่ได้เก็บใน DB แต่อยู่ใน ENV ของโปรเจกต์:
--   NEXT_PUBLIC_DEV_SECRET=LPWELL2026   (ใน .env.local และ Vercel Env)
--   DEV_SECRET=LPWELL2026               (ฝั่ง server, ใช้ตรวจ POST)
-- เปลี่ยนค่าแล้ว redeploy — URL จะเป็น ?dev_secret=ค่าใหม่
-- ดูคำอธิบายเพิ่มใน src/lib/maintenance.ts
